The ``1-my_list`` module
========================

Using ``MyList`` 
----------------

First import ``MyList`` from the ``1-my_list`` module

    >>> MyList = __import__('1-my_list').MyList

Testing for module documentation:
    >>> mod = __import__("1-my_list").__doc__
    >>> len(mod) > 1
    True

Testing for class documentation:
    >>> cl = __import__("1-my_list").MyList.__doc__
    >>> len(cl) > 1
    True


Testing for an empty list:
    >>> my_list = MyList()
    >>> my_list.print_sorted()
    []


Testing a list in correct order (ascending sort):
    >>> my_list = MyList([1, 2, 3, 4])
    >>> print(my_list)
    [1, 2, 3, 4]

    >>> my_list.print_sorted()
    [1, 2, 3, 4]


Testing a list in arbitrary order:
    >>> my_list = MyList([4, 2, 1, 5])
    >>> print(my_list)
    [4, 2, 1, 5]

    >>> my_list.print_sorted()
    [1, 2, 4, 5]

Testing using append method:
    >>> my_list = MyList()
    >>> print(my_list)
    []

    >>> my_list.append(3)
    >>> my_list.append(5)
    >>> my_list.append(1)
    >>> my_list.append(10)
    >>> my_list.append(2)
    >>> print(my_list)
    [3, 5, 1, 10, 2]

    >>> my_list.print_sorted()
    [1, 2, 3, 5, 10]


Testing a list of strings:

    >>> my_list = MyList()
    >>> print(my_list)
    []

    >>> my_list.append("Hajar")
    >>> my_list.append("Hello")
    >>> my_list.append("Alx")
    >>> my_list.append("School")
    >>> my_list.append("Python")
    >>> print(my_list)
    ['Hajar', 'Hello', 'Alx', 'School', 'Python']

    >>> my_list.print_sorted()
    ['Alx', 'Hajar', 'Hello', 'Python', 'School']


Testing a list of differents types, a TypeError is raised
    >>> my_list = MyList()
    >>> my_list.append(1)
    >>> my_list.append(3)
    >>> my_list.append("Alx")
    >>> my_list.append("School")
    >>> my_list.append(10)
    >>> my_list.print_sorted()
    Traceback (most recent call last):
    TypeError: '<' not supported between instances of 'str' and 'int'


Testing with more than one argument, a TypeError is raised
    >>> my_list = MyList([1, 2, 3], [3, 5, 4])
    Traceback (most recent call last):
    TypeError: list expected at most 1 argument, got 2
